apiVersion: "decco.platform9.com/v1beta2"
kind: "Space"
metadata:
  namespace: "decco"
  name: "bad-space"
spec:
  domainName: dummy.net
  httpCertSecretName: dummy
  tcpCertAndCaSecretName: dummy
  encryptHttp: true
  project: dev
