apiVersion: "decco.platform9.com/v1beta2"
kind: "Space"
metadata:
  namespace: "decco"
  name: "dev-1"
spec:
  domainName: platform9.horse
  httpCertSecretName: pf9-horse-secret
  tcpCertAndCaSecretName: dev-1-secret
  encryptHttp: true
  project: dev
