apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sniff
  namespace: decco
  labels:
    role: k8sniff
spec:
  replicas: 1
  selector:
    matchLabels:
      role: k8sniff
  template:
    metadata:
      labels:
        role: k8sniff
    spec:
      serviceAccountName: k8sniff
      containers:
      - image: platform9systems/k8sniff:103
        name: k8sniff
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - -x
          - "/pipeline/source/k8sniff -logtostderr --v=3 --config /etc/config/k8sniff.json"
        ports:
        - name: https
          containerPort: 8443
        resources:
          requests:
             cpu: 900m
             memory: 512Mi
        volumeMounts:
        - name: k8sniff-config
          mountPath: /etc/config
          readOnly: true
      volumes:
        - name: k8sniff-config
          configMap:
            name: k8sniff-configmap
