apiVersion: "decco.platform9.com/v1beta2"
kind: "App"
metadata:
  name: "couchdb"
spec:
  initialReplicas: 1
  endpoints:
  - name: couchdb
    httpPath: "/couchdb"
    rewritePath: "/"
    port: 5984
  pod:
    containers:
    - name: couchdb
      image: couchdb
      ports:
      - containerPort: 5984
