apiVersion: "decco.platform9.com/v1beta2"
kind: "App"
metadata:
  name: "couchdb"
spec:
  initialReplicas: 1
  httpUrlPath: "/couchdb"
  pod:
    containers:
    - name: couchdb
      image: couchdb
      ports:
      - containerPort: 5984