apiVersion: "decco.platform9.com/v1beta2"
kind: "App"
metadata:
  name: "keystone"
spec:
  initialReplicas: 1
  httpPath: "/keystone"
  rewritePath: "/"
  pod:
    containers:
    - name: keystone
      image: monasca/keystone
      ports:
      - containerPort: 5000

