apiVersion: "decco.platform9.com/v1beta2"
kind: "App"
metadata:
  name: "wordpress"
spec:
  httpUrlPath: "/wordpress"
  container:
    name: wordpress
    image: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql.default.svc.cluster.local
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: mysql-pwd
    ports:
    - containerPort: 80
